package com.example.day_02_zuoye2.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.day_02_zuoye2.DataDb;

import com.example.day_02_zuoye2.dao.DataDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDbDaoConfig;

    private final DataDbDao dataDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDbDaoConfig = daoConfigMap.get(DataDbDao.class).clone();
        dataDbDaoConfig.initIdentityScope(type);

        dataDbDao = new DataDbDao(dataDbDaoConfig, this);

        registerDao(DataDb.class, dataDbDao);
    }
    
    public void clear() {
        dataDbDaoConfig.clearIdentityScope();
    }

    public DataDbDao getDataDbDao() {
        return dataDbDao;
    }

}
